const esbuild = require("esbuild");
const process = require("node:process");
const builtinModules = require("builtin-modules");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const isProd = process.argv[2] === "production";

esbuild
	.context({
		banner: {
			js: banner,
		},
		entryPoints: ["main.ts"],
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/*",
			"@lezer/*",
			...builtinModules,
			...builtinModules.map((m) => `node:${m}`),
		],
		format: "cjs",
		target: "es2022",
		logLevel: "info",
		sourcemap: isProd ? false : "inline",
		treeShaking: true,
		outfile: "main.js",
	})
	.then((context) => {
		if (isProd) {
			context
				.rebuild()
				.then(() => {
					process.exit(0);
				})
				.catch((err) => {
					console.error(err);
					process.exit(1);
				});
		} else {
			context.watch().catch((err) => {
				console.error(err);
			});
		}
	})
	.catch((err) => {
		console.error(err);
		process.exit(1);
	});
